name: ai_pc_builder_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
 
